CREATE TABLE `USER_GUEST` (
  `ID_USER` varchar(50) NOT NULL,
  `EMAIL` varchar(50) DEFAULT NULL,
  `HISTO_JSON` text,
  `CDATE` datetime DEFAULT NULL,
  PRIMARY KEY (`ID_USER`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `USER_LOG` (
  `ID_USER` varchar(50) NOT NULL,
  `DATE_DEBUT` datetime NOT NULL,
  `DATE_FIN` datetime DEFAULT NULL,
  PRIMARY KEY (`ID_USER`,`DATE_DEBUT`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `USER_LOG_IP` (
  `ID_USER` varchar(50) NOT NULL,
  `IP_USER` varchar(15) DEFAULT NULL,
  `CDATE` datetime NOT NULL,
  PRIMARY KEY (`ID_USER`,`CDATE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE `USER`   
  ADD COLUMN `HISTO_JSON` TEXT NULL AFTER `FACT_NOM`;

ALTER TABLE `USER`   
  ADD COLUMN `MOT_PASSE_TMP` TEXT NULL AFTER `MOT_PASSE`;

CREATE TABLE `COMMANDE_TMP`(  
  `ID_COMMANDE` VARCHAR(50) NOT NULL,
  `ID_USER` VARCHAR(50),
  `DATE` DATETIME,
  `ACHATS` TEXT,
  `FACT_NOM` VARCHAR(50),
  `FACT_ADR` VARCHAR(80),
  `FACT_CP` VARCHAR(10),
  `FACT_VILLE` VARCHAR(30),
  `FACT_PAYS` VARCHAR(20),
  `PRIX` FLOAT,
  `FRAIS_PORT` FLOAT,
  `MODE_PAIEMENT` ENUM('ogone','credit','cheque_vir'),
  PRIMARY KEY (`ID_COMMANDE`)
);

ALTER TABLE `COMMANDE_TMP`   
  ADD COLUMN `COMMANDE_NO_COMMANDE` VARCHAR(50) NULL AFTER `MODE_PAIEMENT`,
  ADD COLUMN `CREDIT_NO_COMMANDE` VARCHAR(50) NULL AFTER `COMMANDE_NO_COMMANDE`;

ALTER TABLE `ACHAT`   
  ADD COLUMN `TYPE` VARCHAR(1) DEFAULT 'P'  NOT NULL AFTER `PRIX`;

ALTER TABLE `COMMANDE_TMP`   
  ADD COLUMN `NOM` VARCHAR(30) NULL AFTER `FACT_PAYS`,
  ADD COLUMN `PRENOM` VARCHAR(20) NULL AFTER `NOM`,
  ADD COLUMN `ADRESSE` VARCHAR(80) NULL AFTER `PRENOM`,
  ADD COLUMN `CP` VARCHAR(10) NULL AFTER `ADRESSE`,
  ADD COLUMN `VILLE` VARCHAR(30) NULL AFTER `CP`,
  ADD COLUMN `PAYS` VARCHAR(20) NULL AFTER `VILLE`;

ALTER TABLE `USER_LOG_IP`   
  CHANGE `ID_USER` `ID_USER_IP` VARCHAR(50) CHARSET utf8 COLLATE utf8_general_ci NOT NULL,
  ADD COLUMN `ID_USER` VARCHAR(50) NOT NULL AFTER `ID_USER_IP`;

ALTER TABLE `USER_LOG_IP`   
  ADD COLUMN `DATE_FIN` DATETIME NULL AFTER `CDATE`;

ALTER TABLE `CREDIT_ARTICLE`   
  ADD COLUMN `PRIX_CMD` VARCHAR(10) NULL AFTER `PRIX`;

ALTER TABLE `USER`   
  ADD COLUMN `ADMIN` tinyint(1) NOT NULL DEFAULT '0';

ALTER TABLE `USER_LOG_IP`   
  ADD COLUMN `TOUCH_DATE` DATETIME NULL AFTER `DATE_FIN`;

ALTER TABLE `USER_LOG`   
  ADD COLUMN `TOUCH_DATE` DATETIME NULL AFTER `DATE_FIN`;

ALTER TABLE `USER_LOG`   
  ADD COLUMN `ID_USER_LOG` VARCHAR(50) NOT NULL FIRST, 
  DROP PRIMARY KEY,
  ADD PRIMARY KEY (`ID_USER`, `DATE_DEBUT`, `ID_USER_LOG`);

ALTER TABLE `COMMANDE_LOG` 
	ADD COLUMN `DATE` DATETIME NULL AFTER `ID_MODEPAIEMENT`, 
	ADD COLUMN `ID_USER` VARCHAR(50) NULL AFTER `DATE`, 
	ADD COLUMN `FACT_NOM` VARCHAR(50) NULL AFTER `ID_USER`, 
	ADD COLUMN `FACT_ADR` VARCHAR(80) NULL AFTER `FACT_NOM`, 
	ADD COLUMN `FACT_CP` VARCHAR(10) NULL AFTER `FACT_ADR`, 
	ADD COLUMN `FACT_VILLE` VARCHAR(30) NULL AFTER `FACT_CP`, 
	ADD COLUMN `FACT_PAYS` VARCHAR(20) NULL AFTER `FACT_VILLE`, 
	ADD COLUMN `NOM` VARCHAR(30) NULL AFTER `FACT_PAYS`, 
	ADD COLUMN `PRENOM` VARCHAR(20) NULL AFTER `NOM`, 
	ADD COLUMN `ADRESSE` VARCHAR(80) NULL AFTER `PRENOM`, 
	ADD COLUMN `CP` VARCHAR(10) NULL AFTER `ADRESSE`, 
	ADD COLUMN `VILLE` VARCHAR(30) NULL AFTER `CP`, 
	ADD COLUMN `PAYS` VARCHAR(20) NULL AFTER `VILLE`; 

ALTER TABLE `USER_LOG`   
  ADD COLUMN `ALERT_EJECT` INT(1) DEFAULT 0  NULL AFTER `TOUCH_DATE`;

/*
 * Allongement des champs PAYS (jusque la limités à 20 caractères
 */
ALTER TABLE `USER`   
  CHANGE `PAYS` `PAYS` VARCHAR(50) CHARSET utf8 COLLATE utf8_general_ci DEFAULT ''  NOT NULL,
  CHANGE `FACT_PAYS` `FACT_PAYS` VARCHAR(50) CHARSET utf8 COLLATE utf8_general_ci DEFAULT ''  NOT NULL;

ALTER TABLE `COMMANDE_LOG`   
  CHANGE `FACT_PAYS` `FACT_PAYS` VARCHAR(50) CHARSET utf8 COLLATE utf8_general_ci NULL,
  CHANGE `PAYS` `PAYS` VARCHAR(50) CHARSET utf8 COLLATE utf8_general_ci NULL;

ALTER TABLE `COMMANDE_TMP`   
  CHANGE `FACT_PAYS` `FACT_PAYS` VARCHAR(50) CHARSET utf8 COLLATE utf8_general_ci NULL,
  CHANGE `PAYS` `PAYS` VARCHAR(50) CHARSET utf8 COLLATE utf8_general_ci NULL;