/*
 * Tables servant au stockage des logs des recherches
 */
CREATE TABLE `RECH_LOG`(  
  `DATE` DATETIME NOT NULL,
  `IP` VARCHAR(20) NOT NULL,
  `SESSION_ID` VARCHAR(40) NOT NULL,
  `INST` VARCHAR(30) NOT NULL,
  `USER` VARCHAR(30),
  `SEARCH_TERM` TEXT NOT NULL,
  `SEARCHT` TEXT NOT NULL,
  PRIMARY KEY (`DATE`, `IP`, `SESSION_ID`, `INST`, `SEARCH_TERM`(50))
);

ALTER TABLE `RECH_LOG`   
  ADD COLUMN `SEARCHT` TEXT NULL AFTER `SEARCH_TERM`;
