ALTER TABLE `NUMERO`   
  ADD COLUMN `DOI` VARCHAR(40) NULL AFTER `STATUT`;

ALTER TABLE `CAIRN_REFERENCES`   
  CHANGE `ID_CAIRN_CIBLE` `ID_CAIRN_CIBLE` VARCHAR(30) DEFAULT ''  NULL,
  ADD COLUMN `ID_CAIRN_NUM` VARCHAR(30) DEFAULT ''  NULL AFTER `ID_CAIRN_CIBLE`;

ALTER TABLE `NUMERO`
  ADD COLUMN `PRIX_ELEC` FLOAT DEFAULT 0 NOT NULL AFTER `PRIX`;

INSERT INTO MODE_PAIEMENT (ID_MODEPAIEMENT, LIBELLE) 
  VALUES (6,'Crédit d''articles');

ALTER TABLE `NUMERO`   
  ADD COLUMN `DATEMAJ` timestamp NOT NULL default CURRENT_TIMESTAMP AFTER `ID_NUMPUBLIE_S`;

ALTER TABLE `NUMERO`   
  ADD COLUMN `EPUB` INT(1) DEFAULT 0  NULL AFTER `DATEMAJ`;
 

CREATE VIEW `docsRS` 
    AS
(SELECT * FROM evidensse.`docsRS`);

CREATE VIEW `meta` 
    AS
(SELECT * FROM evidensse.`meta`);

/* Modification concerant la nouvelle règlementation TVA : 
 * appliquer la TVA en fonction du pays de facturation
 */
ALTER TABLE `PAYS_EU`   
  ADD COLUMN `TAUX_TVA` FLOAT NULL AFTER `PAYS`,
  ADD COLUMN `TAUX_TVA_REDUIT` FLOAT NULL AFTER `TAUX_TVA`;

ALTER TABLE `REVUE`   
  ADD COLUMN `DATEMAJ` timestamp NOT NULL default CURRENT_TIMESTAMP AFTER `ID_REVUE_S`;

    ALTER TABLE `LICENCE`   
  ADD COLUMN `DATEMAJ` timestamp NOT NULL default CURRENT_TIMESTAMP AFTER `LIBELLE`;

ALTER TABLE `LICENCE_REVUE`   
  ADD COLUMN `DATEMAJ` timestamp NOT NULL default CURRENT_TIMESTAMP AFTER `ID_REVUE`; 

ALTER TABLE `LICENCE_I`   
  ADD COLUMN `DATEMAJ` timestamp NOT NULL default CURRENT_TIMESTAMP AFTER `ID_USER`; 

ALTER TABLE `AUTEUR`   
  ADD COLUMN `DATEMAJ` timestamp NOT NULL default CURRENT_TIMESTAMP AFTER `PAYS`;

ALTER TABLE `AUTEUR_ART`   
  ADD COLUMN `DATEMAJ` timestamp NOT NULL default CURRENT_TIMESTAMP AFTER `OFFPRINT`;

ALTER TABLE `DIS_REVUE`   
  ADD COLUMN `DATEMAJ` timestamp NOT NULL default CURRENT_TIMESTAMP AFTER `POS_DISC`; 

ALTER TABLE `RESUMES`   
  ADD COLUMN `DATEMAJ` timestamp NOT NULL AFTER `mdate`;